steps:

# Build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/homeinfrastructures/noip-autoupdater", "."]

# Push the container image to Container Registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/homeinfrastructures/noip-autoupdater"]

# Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args: [
    "beta", "run", "deploy", "noip-autoupdater", "--image", "gcr.io/homeinfrastructures/noip-autoupdater",
    "--region", "us-west1",
    "--platform", "managed",
    "--allow-unauthenticated"
  ]

images:
  - gcr.io/homeinfrastructures/noip-autoupdater
